- name: authentik setup
  hosts: dockerauthentik.odnops.com
  become: yes  # Remove this if you don't need sudo
  vars:
    files_to_copy:
      - src: ../files/authentik/docker-compose.yaml
        dest: /home/user/docker-compose.yml
      - src: ../files/authentik/.env
        dest: /home/user/.env

  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ item.dest | dirname }}"
        state: directory
        mode: '0755'
      loop: "{{ files_to_copy }}"
      loop_control:
        label: "{{ item.dest }}"

    - name: Copy files to remote host
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop: "{{ files_to_copy }}"
      loop_control:
        label: "{{ item.src }}"
        
    - name: start docker containers
      community.docker.docker_compose_v2:
        project_src: /home/user/
        state: present
        recreate: always